-- 租户业务库数据库
-- 运单表（商品车运输专用，替代原 biz_order）
CREATE TABLE `biz_waybill` (
  `waybill_no` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '运单号',
  `customer_id` bigint DEFAULT NULL COMMENT '客户ID',
  `customer_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客户名称',
  `origin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '出发地',
  `origin_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '出发地编码',
  `origin_region_id` bigint DEFAULT NULL COMMENT '出发地行政区ID',
  `destination` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目的地',
  `destination_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '目的地编码',
  `destination_region_id` bigint DEFAULT NULL COMMENT '目的地行政区ID',
  `vehicle_brand` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车辆品牌',
  `vehicle_model` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车型',
  `quantity` int NOT NULL COMMENT '数量',
  `plan_issue_time` datetime DEFAULT NULL COMMENT '计划下发时间',
  `required_load_time` datetime DEFAULT NULL COMMENT '要求装车时间',
  `required_deliver_time` datetime DEFAULT NULL COMMENT '要求送达时间',
  `dealer_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '经销商名称',
  `dealer_contact` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '经销商联系人',
  `dealer_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '经销商电话',
  `dealer_address` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '经销商地址',
  `freight_amount` decimal(12,2) DEFAULT NULL COMMENT '运费金额',
  `freight_source` smallint DEFAULT NULL COMMENT '运费来源 0-自动计算 1-手动填写',
  `contract_id` bigint DEFAULT NULL COMMENT '合同ID',
  `rate_id` bigint DEFAULT NULL COMMENT '运价ID',
  `status` smallint NOT NULL COMMENT '状态 0-待确认 1-已确认 2-已调度 3-运输中 4-已送达 5-已完成 6-已取消',
  `calc_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT '计算状态',
  `is_locked` smallint NOT NULL DEFAULT '0' COMMENT '是否锁定',
  `waybill_version` int NOT NULL DEFAULT '1' COMMENT '运单版本号',
  `last_calc_at` datetime DEFAULT NULL COMMENT '最近一次正式计算时间',
  `last_result_id` bigint DEFAULT NULL COMMENT '最近一次计算结果主表ID',
  `remark` text COLLATE utf8mb4_unicode_ci COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人ID',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  `is_deleted` smallint NOT NULL DEFAULT '0' COMMENT '是否删除 0-否 1-是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `waybill_no` (`waybill_no`),
  KEY `idx_calc_status` (`calc_status`)
) ENGINE=InnoDB AUTO_INCREMENT=210 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运单表';
