--租户业务库数据库
-- 运单表
CREATE TABLE `biz_order` (
  `order_no` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '运单号',
  `customer_id` bigint DEFAULT NULL COMMENT '客户ID',
  `customer_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客户名称',
  `vehicle_id` bigint DEFAULT NULL COMMENT '车辆ID',
  `plate_number` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '车牌号',
  `driver_id` bigint DEFAULT NULL COMMENT '驾驶员ID',
  `driver_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '驾驶员姓名',
  `route_id` bigint DEFAULT NULL COMMENT '路线ID',
  `origin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '起点',
  `destination` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '终点',
  `cargo_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '货物名称',
  `cargo_weight` decimal(10,2) DEFAULT NULL COMMENT '货物重量（吨）',
  `cargo_volume` decimal(10,2) DEFAULT NULL COMMENT '货物体积（立方米）',
  `freight_amount` decimal(12,2) DEFAULT NULL COMMENT '运费金额',
  `plan_depart_time` datetime DEFAULT NULL COMMENT '计划发车时间',
  `actual_depart_time` datetime DEFAULT NULL COMMENT '实际发车时间',
  `plan_arrive_time` datetime DEFAULT NULL COMMENT '计划到达时间',
  `actual_arrive_time` datetime DEFAULT NULL COMMENT '实际到达时间',
  `status` smallint NOT NULL COMMENT '状态 0-待派车 1-已派车 2-运输中 3-已到达 4-已签收 5-已完成 6-已取消',
  `remark` text COLLATE utf8mb4_unicode_ci COMMENT '备注',
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `created_at` datetime NOT NULL DEFAULT (now()) COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT (now()) COMMENT '更新时间',
  `is_deleted` smallint NOT NULL DEFAULT '0' COMMENT '是否删除 0-否 1-是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='运单表';