"""customer_recon_adjust_approval

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260813_004"
MIGRATION_NAME = "customer_recon_adjust_approval"

REQUIRES_TABLES = ['biz_customer_recon']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    if not _col_exists(conn, "biz_customer_recon", "adjust_amount_total"):
        conn.execute(text(
            "ALTER TABLE `biz_customer_recon` ADD COLUMN `adjust_amount_total` NUMERIC(14, 2) NOT NULL DEFAULT 0 COMMENT '行调整额合计（可负）；超过阈值需业务主管审批后才能确认'"
        ))

    if not _col_exists(conn, "biz_customer_recon", "adjust_approved_at"):
        conn.execute(text(
            "ALTER TABLE `biz_customer_recon` ADD COLUMN `adjust_approved_at` DATETIME NULL COMMENT '大额调整审批时间；调整额再次变动会清空，需重新审批'"
        ))

    if not _col_exists(conn, "biz_customer_recon", "adjust_approved_by"):
        conn.execute(text(
            "ALTER TABLE `biz_customer_recon` ADD COLUMN `adjust_approved_by` BIGINT NULL COMMENT '大额调整审批人 user_id'"
        ))

    return None

