"""finance_base_task_doc_evolve_driver_settlement

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260703_001"
MIGRATION_NAME = "finance_base_task_doc_evolve_driver_settlement"

REQUIRES_TABLES = ['biz_driver_operation', 'biz_task', 'biz_task_finance_doc']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    # NOTE: 新表 `biz_driver_settlement_config` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_finance_doc_event` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    if not _col_exists(conn, "biz_driver_operation", "settlement_mode"):
        conn.execute(text(
            "ALTER TABLE `biz_driver_operation` ADD COLUMN `settlement_mode` SMALLINT NOT NULL DEFAULT 2 COMMENT '结算模式 1-承包制 2-统一管理各费用 3-计件提成'"
        ))

    if not _col_exists(conn, "biz_task", "contracted_amount"):
        conn.execute(text(
            "ALTER TABLE `biz_task` ADD COLUMN `contracted_amount` NUMERIC(12, 2) NOT NULL DEFAULT 0 COMMENT '已承包结算金额（冗余，承包单 doc_type=4 已支付合计）'"
        ))

    if not _col_exists(conn, "biz_task", "is_locked"):
        conn.execute(text(
            "ALTER TABLE `biz_task` ADD COLUMN `is_locked` SMALLINT NOT NULL DEFAULT 0 COMMENT '是否锁定 0-否 1-是（最终结算单/承运商结算单支付后置1，禁改成本字段）'"
        ))

    if not _col_exists(conn, "biz_task", "is_payroll_bound"):
        conn.execute(text(
            "ALTER TABLE `biz_task` ADD COLUMN `is_payroll_bound` SMALLINT NOT NULL DEFAULT 0 COMMENT '是否已挂入司机工资单（软标记，预留）'"
        ))

    if not _col_exists(conn, "biz_task", "is_recon_bound"):
        conn.execute(text(
            "ALTER TABLE `biz_task` ADD COLUMN `is_recon_bound` SMALLINT NOT NULL DEFAULT 0 COMMENT '是否已挂入承运商对账单（软标记，预留）'"
        ))

    if not _col_exists(conn, "biz_task", "locked_at"):
        conn.execute(text(
            "ALTER TABLE `biz_task` ADD COLUMN `locked_at` DATETIME NULL COMMENT '锁定时间'"
        ))

    if not _col_exists(conn, "biz_task", "locked_by_doc_id"):
        conn.execute(text(
            "ALTER TABLE `biz_task` ADD COLUMN `locked_by_doc_id` BIGINT NULL COMMENT '锁定来源财务单据 ID'"
        ))

    if not _col_exists(conn, "biz_task", "payroll_settled"):
        conn.execute(text(
            "ALTER TABLE `biz_task` ADD COLUMN `payroll_settled` SMALLINT NOT NULL DEFAULT 0 COMMENT '司机工资单是否已发放（冗余，预留）'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "cancel_reason"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `cancel_reason` VARCHAR(255) NULL COMMENT '撤销原因（撤销/强制撤销必填）'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "cancelled_at"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `cancelled_at` DATETIME NULL COMMENT '撤销时间'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "cancelled_by"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `cancelled_by` BIGINT NULL COMMENT '撤销操作人 user_id'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "direction"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `direction` SMALLINT NOT NULL DEFAULT 2 COMMENT '收/付方向 1-收款（应收） 2-付款（应付），任务级费用单恒为 2'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "doc_kind"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `doc_kind` VARCHAR(30) NOT NULL DEFAULT 'task_finance' COMMENT '单据大类（冗余常量 task_finance，对齐 FinanceDocBaseMixin）'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "idempotency_key"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `idempotency_key` VARCHAR(64) NULL COMMENT '幂等键（远期写库唯一索引）'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "is_locked"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `is_locked` SMALLINT NOT NULL DEFAULT 0 COMMENT '是否锁定（终态后置 1）'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "locked_at"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `locked_at` DATETIME NULL COMMENT '锁定时间'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "locked_by_doc_id"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `locked_by_doc_id` BIGINT NULL COMMENT '锁定来源单据 ID'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "period_end"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `period_end` DATETIME NULL COMMENT '结算周期止（承包单必填）'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "period_start"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `period_start` DATETIME NULL COMMENT '结算周期起（承包单必填）'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "submitted_at"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `submitted_at` DATETIME NULL COMMENT '提交审批时间'"
        ))

    if not _col_exists(conn, "biz_task_finance_doc", "submitted_by"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` ADD COLUMN `submitted_by` BIGINT NULL COMMENT '提交审批人 user_id'"
        ))

    # ALTER `biz_task_finance_doc.doc_type`
    # - comment: '单据类型 1-预付单 2-补款单 3-结算单' -> '单据类型 1-预付单 2-补款单 3-结算单 4-承包单'
    if _col_exists(conn, "biz_task_finance_doc", "doc_type"):
        conn.execute(text(
            "ALTER TABLE `biz_task_finance_doc` MODIFY COLUMN `doc_type` SMALLINT NOT NULL COMMENT '单据类型 1-预付单 2-补款单 3-结算单 4-承包单'"
        ))

