"""add enterprise_id to customer carrier waybill

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260706_005"
MIGRATION_NAME = "add enterprise_id to customer carrier waybill"

REQUIRES_TABLES = ['biz_carrier', 'biz_customer', 'biz_waybill']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    if not _col_exists(conn, "biz_carrier", "enterprise_id"):
        conn.execute(text(
            "ALTER TABLE `biz_carrier` ADD COLUMN `enterprise_id` BIGINT NULL COMMENT '默认经营主体ID（biz_business_entity.id），承运成本归属默认带出，空=租户默认主体'"
        ))

    if not _index_exists(conn, "biz_carrier", "ix_biz_carrier_enterprise_id"):
        conn.execute(text(
            "CREATE INDEX `ix_biz_carrier_enterprise_id` ON `biz_carrier` (`enterprise_id`)"
        ))

    if not _col_exists(conn, "biz_customer", "enterprise_id"):
        conn.execute(text(
            "ALTER TABLE `biz_customer` ADD COLUMN `enterprise_id` BIGINT NULL COMMENT '默认经营主体ID（biz_business_entity.id），运单收入归属默认带出，空=租户默认主体'"
        ))

    if not _index_exists(conn, "biz_customer", "ix_biz_customer_enterprise_id"):
        conn.execute(text(
            "CREATE INDEX `ix_biz_customer_enterprise_id` ON `biz_customer` (`enterprise_id`)"
        ))

    if not _col_exists(conn, "biz_waybill", "enterprise_id"):
        conn.execute(text(
            "ALTER TABLE `biz_waybill` ADD COLUMN `enterprise_id` BIGINT NULL COMMENT '收入归属经营主体ID（biz_business_entity.id），默认取客户主体，可改，空=租户默认主体'"
        ))

    if not _index_exists(conn, "biz_waybill", "ix_biz_waybill_enterprise_id"):
        conn.execute(text(
            "CREATE INDEX `ix_biz_waybill_enterprise_id` ON `biz_waybill` (`enterprise_id`)"
        ))

