"""recon_diff_table

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260813_002"
MIGRATION_NAME = "recon_diff_table"

REQUIRES_TABLES = ['biz_finance_doc_event']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    # NOTE: 新表 `biz_recon_diff` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # ALTER `biz_finance_doc_event.event_type`
    # - comment: '事件类型 1-创建 2-提交 3-审批通过 4-审批拒绝 5-退回草稿 6-支付 7-撤销支付 8-撤销 9-强制撤销 10-核销 11-锁定 12-解锁 13-开票 14-作废 15-红冲' -> '事件类型 1-创建 2-提交 3-审批通过 4-审批拒绝 5-退回草稿 6-支付 7-撤销支付 8-撤销 9-强制撤销 10-核销 11-锁定 12-解锁 13-开票 14-作废 15-红冲 16-金额调整 17-差异登记 18-差异关闭 19-强制确认 20-重算刷新'
    if _col_exists(conn, "biz_finance_doc_event", "event_type"):
        conn.execute(text(
            "ALTER TABLE `biz_finance_doc_event` MODIFY COLUMN `event_type` SMALLINT NOT NULL COMMENT '事件类型 1-创建 2-提交 3-审批通过 4-审批拒绝 5-退回草稿 6-支付 7-撤销支付 8-撤销 9-强制撤销 10-核销 11-锁定 12-解锁 13-开票 14-作废 15-红冲 16-金额调整 17-差异登记 18-差异关闭 19-强制确认 20-重算刷新'"
        ))

    return None

