"""task_alert_tables

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260812_001"
MIGRATION_NAME = "task_alert_tables"

REQUIRES_TABLES = ['biz_task_alert_rule']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    if not _col_exists(conn, "biz_task_alert_rule", "anchor_offset_minutes"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` ADD COLUMN `anchor_offset_minutes` INTEGER NULL COMMENT '锚点允许时长（分钟）：DEPART/DELIVER 类以「实际装车/到达时间 + 本值」为应完成时间'"
        ))

    if not _col_exists(conn, "biz_task_alert_rule", "stage"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` ADD COLUMN `stage` SMALLINT NULL COMMENT '限定阶段（仅 STAGE_STAGNANT 需要逐阶段配置；其余规则码阶段已隐含，留空）'"
        ))

    return None

