"""task status event and stage entered at

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260810_001"
MIGRATION_NAME = "task status event and stage entered at"

REQUIRES_TABLES = ['biz_task', 'biz_task_waybill_item', 'biz_waybill']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    # NOTE: 新表 `biz_task_status_event` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    if not _col_exists(conn, "biz_task", "stage_entered_at"):
        conn.execute(text(
            "ALTER TABLE `biz_task` ADD COLUMN `stage_entered_at` DATETIME NULL COMMENT '进入当前状态的时间（每次状态变更同步物化，用于阶段停留时长与滞留预警）'"
        ))

    # 以下均为「签收 → 交车」文案对齐产生的纯注释变更（不改类型、默认值与可空性）
    if _col_exists(conn, "biz_task", "status"):
        conn.execute(text(
            "ALTER TABLE `biz_task` MODIFY COLUMN `status` SMALLINT NOT NULL DEFAULT 0 "
            "COMMENT '状态 0-待派车 1-已派车 2-已装车 3-在途 4-已到达 5-已交车(聚合态) 7-已关闭 9-已取消'"
        ))

    if _col_exists(conn, "biz_task_waybill_item", "status"):
        conn.execute(text(
            "ALTER TABLE `biz_task_waybill_item` MODIFY COLUMN `status` SMALLINT NOT NULL DEFAULT 0 "
            "COMMENT '状态 0-待装车 1-已装车 2-已卸车 3-已交车'"
        ))

    if _col_exists(conn, "biz_task_waybill_item", "signed_at"):
        conn.execute(text(
            "ALTER TABLE `biz_task_waybill_item` MODIFY COLUMN `signed_at` DATETIME NULL "
            "COMMENT '交车时间'"
        ))

    if _col_exists(conn, "biz_waybill", "status"):
        conn.execute(text(
            "ALTER TABLE `biz_waybill` MODIFY COLUMN `status` SMALLINT NOT NULL "
            "COMMENT '状态 0-待确认 1-待调度 2-调度中 3-运输中 4-待交车 5-已交车 6-已回单 7-已关闭'"
        ))

    if _col_exists(conn, "biz_waybill", "receipt_at"):
        conn.execute(text(
            "ALTER TABLE `biz_waybill` MODIFY COLUMN `receipt_at` DATETIME NULL "
            "COMMENT '回单确认时间（交车回单返还货主）'"
        ))

    return None

