"""alert_rule_dual_clock

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260813_001"
MIGRATION_NAME = "alert_rule_dual_clock"

REQUIRES_TABLES = ['biz_task_alert_rule']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    if not _col_exists(conn, "biz_task_alert_rule", "critical_after_required_minutes"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` ADD COLUMN `critical_after_required_minutes` INTEGER NULL COMMENT '相对客户要求：超时多少分钟升「严重」'"
        ))

    if not _col_exists(conn, "biz_task_alert_rule", "plan_enabled"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` ADD COLUMN `plan_enabled` SMALLINT NOT NULL DEFAULT 1 COMMENT '是否启用内部计划时间这一路 0-关 1-开'"
        ))

    if not _col_exists(conn, "biz_task_alert_rule", "required_enabled"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` ADD COLUMN `required_enabled` SMALLINT NOT NULL DEFAULT 1 COMMENT '是否启用客户要求时间这一路 0-关 1-开'"
        ))

    if not _col_exists(conn, "biz_task_alert_rule", "warn_ahead_required_minutes"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` ADD COLUMN `warn_ahead_required_minutes` INTEGER NULL COMMENT '相对客户要求：提前多少分钟进入「关注」'"
        ))

    # 存量：按原 time_basis 还原两路开关；原阈值抄到客户这一路，升级后行为不变
    conn.execute(text(
        """
        UPDATE `biz_task_alert_rule`
        SET
          plan_enabled = CASE WHEN time_basis IN (0, 2) THEN 1 ELSE 0 END,
          required_enabled = CASE WHEN time_basis IN (1, 2) THEN 1 ELSE 0 END,
          warn_ahead_required_minutes = COALESCE(
            warn_ahead_required_minutes, warn_ahead_minutes
          ),
          critical_after_required_minutes = COALESCE(
            critical_after_required_minutes, critical_after_minutes
          )
        WHERE is_deleted = 0
          AND (
            warn_ahead_required_minutes IS NULL
            OR critical_after_required_minutes IS NULL
            OR (plan_enabled = 1 AND required_enabled = 1 AND time_basis IN (0, 1))
          )
        """
    ))

    # ALTER `biz_task_alert_rule.critical_after_minutes`
    # - comment: '超时多少分钟升「严重」（空=用内置默认，0=一超时即严重）' -> '相对内部计划：超时多少分钟升「严重」'
    if _col_exists(conn, "biz_task_alert_rule", "critical_after_minutes"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` MODIFY COLUMN `critical_after_minutes` INTEGER NULL COMMENT '相对内部计划：超时多少分钟升「严重」'"
        ))

    # ALTER `biz_task_alert_rule.time_basis`
    # - comment: '时间基准 0-内部计划 1-客户要求 2-取更早者' -> '时间基准（派生）0-只看内部 1-只看客户 2-两路都看'
    if _col_exists(conn, "biz_task_alert_rule", "time_basis"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` MODIFY COLUMN `time_basis` SMALLINT NOT NULL DEFAULT 2 COMMENT '时间基准（派生）0-只看内部 1-只看客户 2-两路都看'"
        ))

    # ALTER `biz_task_alert_rule.warn_ahead_minutes`
    # - comment: '提前多少分钟进入「关注」（空=用内置默认）' -> '相对内部计划：提前多少分钟进入「关注」'
    if _col_exists(conn, "biz_task_alert_rule", "warn_ahead_minutes"):
        conn.execute(text(
            "ALTER TABLE `biz_task_alert_rule` MODIFY COLUMN `warn_ahead_minutes` INTEGER NULL COMMENT '相对内部计划：提前多少分钟进入「关注」'"
        ))

    return None

