"""customer_receivable_tables

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260813_003"
MIGRATION_NAME = "customer_receivable_tables"

REQUIRES_TABLES = ['biz_customer', 'biz_finance_doc_event', 'biz_waybill']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    # NOTE: 新表 `biz_customer_recon` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_customer_recon_waybill_link` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_customer_settle_recon_link` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_customer_settlement` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_receipt_settle_link` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_receipt_voucher` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    if not _col_exists(conn, "biz_customer", "credit_limit"):
        conn.execute(text(
            "ALTER TABLE `biz_customer` ADD COLUMN `credit_limit` NUMERIC(14, 2) NULL COMMENT '信用额度（未收余额上限）；空=不限额。超额只预警不拦截'"
        ))

    if not _col_exists(conn, "biz_customer", "credit_status"):
        conn.execute(text(
            "ALTER TABLE `biz_customer` ADD COLUMN `credit_status` SMALLINT NOT NULL DEFAULT 1 COMMENT '信用状态 0-暂停合作 1-正常 2-重点关注（仅作提示依据，不阻断业务）'"
        ))

    if not _col_exists(conn, "biz_customer", "payment_days"):
        conn.execute(text(
            "ALTER TABLE `biz_customer` ADD COLUMN `payment_days` INTEGER NULL COMMENT '账期天数（配合 settlement_type 推导到期日）；空=未设置，按 0 天算'"
        ))

    # ALTER `biz_finance_doc_event.event_type`
    # - comment: '事件类型 1-创建 2-提交 3-审批通过 4-审批拒绝 5-退回草稿 6-支付 7-撤销支付 8-撤销 9-强制撤销 10-核销 11-锁定 12-解锁 13-开票 14-作废 15-红冲 16-金额调整 17-差异登记 18-差异关闭 19-强制确认 20-重算刷新' -> '事件类型 1-创建 2-提交 3-审批通过 4-审批拒绝 5-退回草稿 6-支付 7-撤销支付 8-撤销 9-强制撤销 10-核销 11-锁定 12-解锁 13-开票 14-作废 15-红冲 16-金额调整 17-差异登记 18-差异关闭 19-强制确认 20-重算刷新 21-批次打款 22-到账认领 23-核销冲销 24-进项收票 25-票款核对 26-信用预警'
    if _col_exists(conn, "biz_finance_doc_event", "event_type"):
        conn.execute(text(
            "ALTER TABLE `biz_finance_doc_event` MODIFY COLUMN `event_type` SMALLINT NOT NULL COMMENT '事件类型 1-创建 2-提交 3-审批通过 4-审批拒绝 5-退回草稿 6-支付 7-撤销支付 8-撤销 9-强制撤销 10-核销 11-锁定 12-解锁 13-开票 14-作废 15-红冲 16-金额调整 17-差异登记 18-差异关闭 19-强制确认 20-重算刷新 21-批次打款 22-到账认领 23-核销冲销 24-进项收票 25-票款核对 26-信用预警'"
        ))

    if not _col_exists(conn, "biz_waybill", "is_recon_bound"):
        conn.execute(text(
            "ALTER TABLE `biz_waybill` ADD COLUMN `is_recon_bound` SMALLINT NOT NULL DEFAULT 0 COMMENT '是否已挂入客户对账单 0-否 1-是（软标记，仅供列表徽章展示；拦截判据以桥接表为准，见文档 02 §六）'"
        ))

    if not _col_exists(conn, "biz_waybill", "locked_at"):
        conn.execute(text(
            "ALTER TABLE `biz_waybill` ADD COLUMN `locked_at` DATETIME NULL COMMENT '锁定时间（客户结算单收妥时写入）'"
        ))

    if not _col_exists(conn, "biz_waybill", "locked_by_doc_id"):
        conn.execute(text(
            "ALTER TABLE `biz_waybill` ADD COLUMN `locked_by_doc_id` BIGINT NULL COMMENT '锁定来源单据ID（biz_customer_settlement.id），解锁时校验来源'"
        ))

    return None

