"""add fleet maintenance tables

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260730_001"
MIGRATION_NAME = "add fleet maintenance tables"

REQUIRES_TABLES = []


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    # NOTE: 新表 `biz_fleet_maintain_plan` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_fleet_work_order` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    return None

