"""add fleet parts stock workshop and wo lines

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260731_001"
MIGRATION_NAME = "add fleet parts stock workshop and wo lines"

REQUIRES_TABLES = ['biz_fleet_work_order']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    # NOTE: 新表 `biz_fleet_part` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_fleet_stock_txn` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_fleet_work_order_line` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    # NOTE: 新表 `biz_fleet_workshop` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    if not _col_exists(conn, "biz_fleet_work_order", "fault_category"):
        conn.execute(text(
            "ALTER TABLE `biz_fleet_work_order` ADD COLUMN `fault_category` VARCHAR(50) NULL COMMENT '故障/作业分类'"
        ))

    if not _col_exists(conn, "biz_fleet_work_order", "labor_amount"):
        conn.execute(text(
            "ALTER TABLE `biz_fleet_work_order` ADD COLUMN `labor_amount` NUMERIC(12, 2) NULL COMMENT '工时/项目费用合计'"
        ))

    if not _col_exists(conn, "biz_fleet_work_order", "parts_amount"):
        conn.execute(text(
            "ALTER TABLE `biz_fleet_work_order` ADD COLUMN `parts_amount` NUMERIC(12, 2) NULL COMMENT '备件费用合计'"
        ))

    if not _col_exists(conn, "biz_fleet_work_order", "workshop_id"):
        conn.execute(text(
            "ALTER TABLE `biz_fleet_work_order` ADD COLUMN `workshop_id` BIGINT NULL COMMENT '维修厂ID'"
        ))

    # ALTER `biz_fleet_work_order.workshop`
    # - comment: '维修厂/地点' -> '维修厂/地点（冗余）'
    if _col_exists(conn, "biz_fleet_work_order", "workshop"):
        conn.execute(text(
            "ALTER TABLE `biz_fleet_work_order` MODIFY COLUMN `workshop` VARCHAR(200) NULL COMMENT '维修厂/地点（冗余）'"
        ))

    return None

