"""approval_process_config_tree

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260612_001"
MIGRATION_NAME = "approval_process_config_tree"

REQUIRES_TABLES = ['biz_approval_flow', 'biz_approval_instance', 'biz_approval_instance_node']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    if not _col_exists(conn, "biz_approval_flow", "process_config"):
        conn.execute(text(
            "ALTER TABLE `biz_approval_flow` ADD COLUMN `process_config` JSON NULL COMMENT '可视化画布流程定义（树/条件分支 JSON）；空=走旧线性 flow_node'"
        ))

    if not _col_exists(conn, "biz_approval_instance", "current_node_key"):
        conn.execute(text(
            "ALTER TABLE `biz_approval_instance` ADD COLUMN `current_node_key` VARCHAR(64) NULL COMMENT '当前推进到的节点在画布树内的稳定标识'"
        ))

    if not _col_exists(conn, "biz_approval_instance", "process_config"):
        conn.execute(text(
            "ALTER TABLE `biz_approval_instance` ADD COLUMN `process_config` JSON NULL COMMENT '提交时冻结的画布流程定义快照（树/条件分支 JSON）'"
        ))

    if not _col_exists(conn, "biz_approval_instance_node", "node_key"):
        conn.execute(text(
            "ALTER TABLE `biz_approval_instance_node` ADD COLUMN `node_key` VARCHAR(64) NULL COMMENT '节点在画布树内的稳定标识（线性流程为空）'"
        ))

