"""add fleet renewal and asset card fields

Auto-generated by `python -m scripts.migration.autogen tenant`.

请人工 review，重点检查：
  * 新增 NOT NULL 列：是否需要先 UPDATE 回填，或改成允许 NULL / 提供默认值
  * 改类型 / 改长度：是否会截断现有数据
  * 索引/唯一约束变更：是否会破坏线上正在运行的查询
  * 删除/重命名：autogen 默认生成 NotImplementedError，需人工启用并测试
"""

from sqlalchemy import text

MIGRATION_ID = "20260730_002"
MIGRATION_NAME = "add fleet renewal and asset card fields"

REQUIRES_TABLES = ['biz_vehicle_ext']


_COL_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND column_name = :cn
    LIMIT 1
    """
)

_INDEX_EXISTS_SQL = text(
    """
    SELECT 1 FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = :tn
      AND index_name = :ix
    LIMIT 1
    """
)


def _col_exists(conn, table_name: str, column_name: str) -> bool:
    return conn.execute(
        _COL_EXISTS_SQL, {"tn": table_name, "cn": column_name}
    ).fetchone() is not None


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    return conn.execute(
        _INDEX_EXISTS_SQL, {"tn": table_name, "ix": index_name}
    ).fetchone() is not None


def upgrade(conn, tenant_code: str) -> None:
    # NOTE: 新表 `biz_fleet_renewal` —— 推荐直接由 runner Phase 1 (feature.required_tables) 自动建表。
    # 如本迁移确实需要在租户库强建该表，请改用 metadata.create_all 风格。
    # 此处空操作。

    if not _col_exists(conn, "biz_vehicle_ext", "depreciable_months"):
        conn.execute(text(
            "ALTER TABLE `biz_vehicle_ext` ADD COLUMN `depreciable_months` INTEGER NULL COMMENT '折旧月数'"
        ))

    if not _col_exists(conn, "biz_vehicle_ext", "depreciation_method"):
        conn.execute(text(
            "ALTER TABLE `biz_vehicle_ext` ADD COLUMN `depreciation_method` VARCHAR(32) NULL COMMENT '折旧方法，默认 straight_line'"
        ))

    if not _col_exists(conn, "biz_vehicle_ext", "depreciation_start_date"):
        conn.execute(text(
            "ALTER TABLE `biz_vehicle_ext` ADD COLUMN `depreciation_start_date` DATE NULL COMMENT '折旧起算日'"
        ))

    if not _col_exists(conn, "biz_vehicle_ext", "original_value"):
        conn.execute(text(
            "ALTER TABLE `biz_vehicle_ext` ADD COLUMN `original_value` NUMERIC(14, 2) NULL COMMENT '资产原值（元）'"
        ))

    if not _col_exists(conn, "biz_vehicle_ext", "residual_value"):
        conn.execute(text(
            "ALTER TABLE `biz_vehicle_ext` ADD COLUMN `residual_value` NUMERIC(14, 2) NULL COMMENT '预计残值（元）'"
        ))

    return None

